name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List all files and folders recursively
        run: |
          echo "📁 Listing full directory tree..."
          ls -R

      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: Upload Inventory_build to FTP server
        run: |
          lftp -e "set ssl:verify-certificate no; mirror -R Inventory_build public_html; quit" \
          -u "u436604201.mediumspringgreen-wombat-997457.hostingersite.com,P@ss123#@!123" 82.29.199.121
